package com.main.percobaan12;

public class Eksepsi {
    static void tampil(String s) throws Exception
    {
        System.out.println("tampil");
        if (s.equals("amir")){
            throw new MyException(s);
        }
        System.out.println("OK");
    }

    public static void main(String[] args) throws Exception
    {
        try {
            tampil("ali");
            tampil("amir");
        }catch (Exception e){
            System.out.println("tangkap : "+e);
        }
    }
}

class MyException extends Exception {

    private String Teks;
    MyException(String s){
        Teks = "Exception generated by: " +s;
        System.out.println(Teks);
    }
}
